name: "Red Mushroom Hat"
item: red_mushroom
custom-model-data: 1
model: "blanktopia:hats/red_mushroom_hat"

triggers:
  right-click:
  - type: equip-item
    slot: HEAD
  - type: cancel
  right-click-inventory:
  - type: equip-item
    slot: HEAD
  - type: cancel
  shift-right-click-inventory:
  - type: equip-item
    slot: HEAD
  - type: cancel
  shift-left-click-inventory:
  - type: equip-item
    slot: HEAD
  - type: cancel
  place-block:
  - type: cancel
