version: 2
name: "<transition:#1363d3:#5eeaf2>Cobalt Drill"
item: netherite_pickaxe
custom-model-data: 1
model: "blanktopia:rares/cobalt_drill"
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Can be used as:'
  - '<dark_grey>- <white>Pickaxe'
  - '<dark_grey>- <white>Shovel'
  - '<dark_grey>- <white>Axe'
  - '<dark_grey>- <white>Hoe'
  - ''
  - '<white>Hold <aqua>Sneak<white> to disable'
  - '<aqua>Silk Touch<white>.'
tool:
  default-mining-speed: 9.0
  damage-per-block: 1
  rules:
    - blocks: '#mineable/pickaxe'
      correct-for-drops: true
    - blocks: '#mineable/shovel'
      correct-for-drops: true
    - blocks: '#mineable/axe'
      correct-for-drops: true
    - blocks: '#mineable/hoe'
      correct-for-drops: true
enchantments:
  blanktopia:soulbound: 1
  efficiency: 8
  silk_touch: 1
attributes:
  - amount: 4.0
    attribute: attack_damage
    name: cobalt_drill
    operation: ADD_NUMBER
    slot: HAND
  - amount: 2.0
    attribute: attack_speed
    name: cobalt_drill
    operation: ADD_NUMBER
    slot: HAND
triggers:
  damage-entity:
    - type: play-sound
      pitch: 0.5
      sound: ui.stonecutter.take_result
      volume: 0.3
  right-click:
    - type: play-sound
      pitch: 0.5
      sound: ui.stonecutter.take_result
      volume: 0.3
  left-click-block:
    - type: play-sound
      pitch: 0.5
      sound: ui.stonecutter.take_result
      volume: 0.3
  sneak:
    - type: toggle-enchantment
      enchantment: silk_touch
      level: 1
      name: Silk Touch
      toggled: false
    - type: toggle-enchantment
      enchantment: fortune
      level: 3
      name: Fortune
      toggled: true
  unsneak:
    - type: toggle-enchantment
      enchantment: fortune
      level: 3
      name: Fortune
      toggled: false
    - type: toggle-enchantment
      enchantment: silk_touch
      level: 1
      name: Silk Touch
      toggled: true
