version: 2
name: "&#1363d3-#5eeaf2&Cobalt Drill"
material: NETHERITE_PICKAXE
custom-model-data: 1
model: "blanktopia:rares/cobalt_drill"
models:
  - material: NETHERITE_SHOVEL
    predicate: {custom_model_data: 1}
    model: "blanktopia:rares/cobalt_drill"
  - material: NETHERITE_AXE
    predicate: {custom_model_data: 1}
    model: "blanktopia:rares/cobalt_drill"
  - material: DIAMOND_HOE
    predicate: {custom_model_data: 1}
    model: "blanktopia:rares/cobalt_drill"
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '&fCan be used as:'
  - '&8- &fPickaxe'
  - '&8- &fShovel'
  - '&8- &fAxe'
  - '&8- &fHoe'
  - ''
  - '&fHold &bSneak&f to disable'
  - '&bSilk Touch&f.'
enchantments:
  efficiency: 8
  silk_touch: 1
attributes:
  - amount: 4.0
    attribute: generic.attack_damage
    name: Attack Damage
    operation: ADD_NUMBER
    slot: HAND
    uuid: aa1fcf0e-8d0e-4cc2-b374-bd8ec556eb2d
  - amount: 2.0
    attribute: generic.attack_speed
    name: Attack Speed
    operation: ADD_NUMBER
    slot: HAND
    uuid: cba0af9c-106f-45c9-b88a-006bd4a01dd0
triggers:
  damage-entity:
    - type: play-sound
      pitch: 0.5
      sound: ui.stonecutter.take_result
      volume: 0.3
  right-click-block:
    - type: multi-tool
      tools:
        - NETHERITE_PICKAXE
        - NETHERITE_SHOVEL
        - NETHERITE_AXE
        - DIAMOND_HOE
    - type: play-sound
      pitch: 0.5
      sound: ui.stonecutter.take_result
      volume: 0.3
  left-click-block:
    - type: multi-tool
      tools:
        - NETHERITE_PICKAXE
        - NETHERITE_SHOVEL
        - NETHERITE_AXE
        - DIAMOND_HOE
    - type: play-sound
      pitch: 0.5
      sound: ui.stonecutter.take_result
      volume: 0.3
  sneak:
    - type: toggle-enchantment
      enchantment: silk_touch
      level: 1
      name: Silk Touch
      toggled: false
    - type: toggle-enchantment
      enchantment: fortune
      level: 3
      name: Fortune
      toggled: true
  unsneak:
    - type: toggle-enchantment
      enchantment: fortune
      level: 3
      name: Fortune
      toggled: false
    - type: toggle-enchantment
      enchantment: silk_touch
      level: 1
      name: Silk Touch
      toggled: true
