version: 2
name: "<transition:#1363d3:#5eeaf2>Cobalt Drill"
item: netherite_pickaxe
custom-model-data: 1
model: "blanktopia:rares/cobalt_drill"
models:
  - item: netherite_shovel
    predicate: {custom_model_data: 1}
    model: "blanktopia:rares/cobalt_drill"
  - item: netherite_axe
    predicate: {custom_model_data: 1}
    model: "blanktopia:rares/cobalt_drill"
  - item: diamond_hoe
    predicate: {custom_model_data: 1}
    model: "blanktopia:rares/cobalt_drill"
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Can be used as:'
  - '<dark_grey>- <white>Pickaxe'
  - '<dark_grey>- <white>Shovel'
  - '<dark_grey>- <white>Axe'
  - '<dark_grey>- <white>Hoe'
  - ''
  - '<white>Hold <aqua>Sneak<white> to disable'
  - '<aqua>Silk Touch<white>.'
enchantments:
  blanktopia:soulbound: 1
  efficiency: 8
  silk_touch: 1
attributes:
  - amount: 4.0
    attribute: attack_damage
    name: cobalt_drill
    operation: ADD_NUMBER
    slot: HAND
  - amount: 2.0
    attribute: attack_speed
    name: cobalt_drill
    operation: ADD_NUMBER
    slot: HAND
triggers:
  damage-entity:
    - type: play-sound
      pitch: 0.5
      sound: ui.stonecutter.take_result
      volume: 0.3
  right-click-block:
    - type: multi-tool
      tools:
        - NETHERITE_PICKAXE
        - NETHERITE_SHOVEL
        - NETHERITE_AXE
        - DIAMOND_HOE
    - type: play-sound
      pitch: 0.5
      sound: ui.stonecutter.take_result
      volume: 0.3
  left-click-block:
    - type: multi-tool
      tools:
        - NETHERITE_PICKAXE
        - NETHERITE_SHOVEL
        - NETHERITE_AXE
        - DIAMOND_HOE
    - type: play-sound
      pitch: 0.5
      sound: ui.stonecutter.take_result
      volume: 0.3
  sneak:
    - type: toggle-enchantment
      enchantment: silk_touch
      level: 1
      name: Silk Touch
      toggled: false
    - type: toggle-enchantment
      enchantment: fortune
      level: 3
      name: Fortune
      toggled: true
  unsneak:
    - type: toggle-enchantment
      enchantment: fortune
      level: 3
      name: Fortune
      toggled: false
    - type: toggle-enchantment
      enchantment: silk_touch
      level: 1
      name: Silk Touch
      toggled: true
