version: 1

name: "&6Excavator&c ⛏"
material: IRON_SHOVEL
custom-model-data: 1

unique: true
unbreakable: true

lore: |-
  &8-------------------------
  
  &fShovels in a &b3x3&f area.
  
  &8-------------------------
  &6MINER's Crate Item

enchantments:
  efficiency: 6
  blanktopia:final: 1
  blanktopia:soulbound: 1

triggers:
  break-block:
  - type: if
    if:
      type: not
      not:
        type: is-sneaking
    then:
    - type: break-block
      radius: 1
  right-click-block:
  - type: if
    if:
      type: not
      not:
        type: is-sneaking
    then:
    - type: path-block
      radius: 1
      depth: 1
