version: 1

name: "&6Lumberjack&c ⛏"
material: IRON_AXE
custom-model-data: 1
model: "blanktopia:rares/lumberjack"

unique: true
unbreakable: true

lore: |-
  &8-------------------------
  
  &fChops in a &b3x3&f area.
  
  &8-------------------------
  &6BUILDER's Crate Item

enchantments:
  efficiency: 6
  blanktopia:final: 1
  blanktopia:soulbound: 1

triggers:
  break-block:
  - type: if
    if:
      type: not
      not:
        type: is-sneaking
    then:
    - type: break-block
      radius: 1
  right-click-block:
  - type: if
    if:
      type: not
      not:
        type: is-sneaking
    then:
    - type: strip-block
      radius: 1
