version: 1

name: "&x&2&d&7&a&5&3Scythe"
material: SHEARS
custom-model-data: 1
model: "blanktopia:rares/scythe"

unique: true
unbreakable: true

lore: |-
  &8-------------------------
  
  &fShears in a &b5x5x5&f area.
  
  &8-------------------------
  &6NATURE Crate Item

enchantments:
  efficiency: 6
  sharpness: 5
  blanktopia:final: 1
  blanktopia:soulbound: 1

attributes:
- amount: 5
  attribute: GENERIC_ATTACK_DAMAGE
  name: Tool modifier
  operation: ADD_NUMBER
  slot: HAND
  uuid: 61f83826-cf9e-4239-8b80-dac5367e7507
- amount: -1.5
  attribute: GENERIC_ATTACK_SPEED
  name: Tool modifier
  operation: ADD_NUMBER
  slot: HAND
  uuid: ba636a2c-fa57-4280-a04b-2fae123f4398

triggers:
  break-block:
  - type: if
    if:
      type: not
      not:
        type: is-sneaking
    then:
    - type: break-block
      radius: 2
      depth: 2
  right-click-block:
  - type: if
    if:
      type: not
      not:
        type: is-sneaking
    then:
    - type: till-block
      radius: 2
      depth: 2
    else:
    - type: till-block
