version: 2
name: "&6Wrecking Ball&c ⛏"
material: IRON_PICKAXE
custom-model-data: 1
model: "blanktopia:rares/wrecking_ball"
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '&fMines in a &b3x3&f area.'
enchantments:
  efficiency: 6
  silk_touch: 1
triggers:
  break-block:
    - type: if
      if:
        type: not
        not:
          type: is-sneaking
      then:
        - type: break-block
          radius: 1
