version: 1
name: "<transition:#9cfcf6:#e5fff6>Ambr<transition:#e5fff6:#9cfcf6>osia"
item: bowl
custom-model-data: 2
model: "blanktopia:rares/ambrosia"
soulbound: true
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Grants two additional hearts.'
  - ''
  - '<grey>Slot: <#ff4e1d>Trinket'
slots:
  - TRINKET
triggers:
  equip-armor:
    - type: add-attribute-modifier
      attribute-modifiers:
        - attribute: max_health
          uuid: 50e1e36d-0651-45d6-a41a-8e0ce68828e4
          name: Ambrosia
          amount: 4.0
          operation: ADD_NUMBER
  unequip-armor:
    - type: remove-attribute-modifier
      attribute-modifiers:
        - attribute: max_health
          uuid: 50e1e36d-0651-45d6-a41a-8e0ce68828e4
          name: Ambrosia
          amount: 4.0
          operation: ADD_NUMBER
