version: 1
name: "<transition:#ea4f4f:#fff56d>Booster v2.0"
material: FIREWORK_ROCKET
soulbound: true
unbreakable: true
unique: true
lore:
  - ''
  - '<white>Press <aqua>sneak<white> when gliding'
  - '<white>to boost yourself.'
  - ''
  - '<grey>Slot: <#ff4e1d>&Trinket'
slots:
  - TRINKET
triggers:
  right-click:
    - type: cancel
  tick:
    - type: if
      if:
        type: all
        actions:
          - type: is-gliding
          - type: is-sneaking
      then:
        - type: spawn-particle
          count: 1
          y: 0
          offset-x: 0
          offset-y: 0
          offset-z: 0
          particle: FIREWORK
          extra: 0
        - type: clamp-velocity
          max: 0
        - type: add-velocity
          x: 0
          y: 0
          z: 1.2
          max: 1.2
          rotate-yaw: true
          rotate-pitch: true
        - type: play-sound
          pitch: 0.6
          sound: entity.generic.extinguish_fire
          volume: 0.1
