version: 2
name: "<transition:#f4cf8b:#f79859>Boots of Haste"
item: leather
custom-model-data: 5
model: "blanktopia:rares/boots_of_haste"
enchantments:
  blanktopia:soulbound: 1
enchantment-glint: false
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Allows you to <aqua>sprint<white> faster.'
  - ''
  - '<grey>Slot: <#ff4e1d>Trinket'
slots:
  - TRINKET
triggers:
  tick-slow:
    - type: if
      if:
        type: all
        actions:
          - type: is-on-ground
          - type: is-sprinting
      then:
        - type: spawn-particle
          count: 2
          y: 0.9
          offset-x: 0.3
          offset-y: 0.1
          offset-z: 0.3
          particle: CLOUD
          extra: 0
  sprint:
    - type: if
      if:
        type: all
        actions:
          - type: is-on-ground
          - type: not
            not:
              type: is-sneaking
      then:
        - type: delay
          ticks: 10
          actions:
            - type: if
              if:
                type: is-sprinting
              then:
                - type: add-attribute-modifier
                  attribute-modifiers:
                    - attribute: movement_speed
                      name: boots_of_haste
                      amount: 0.15
                      operation: ADD_SCALAR
                - type: delay
                  ticks: 10
                  actions:
                    - type: if
                      if:
                        type: is-sprinting
                      then:
                        - type: remove-attribute-modifier
                          attribute-modifiers:
                            - attribute: movement_speed
                              name: boots_of_haste
                              amount: 0.15
                              operation: ADD_SCALAR
                        - type: add-attribute-modifier
                          attribute-modifiers:
                            - attribute: movement_speed
                              name: boots_of_haste
                              amount: 0.3
                              operation: ADD_SCALAR
                        - type: delay
                          ticks: 10
                          actions:
                            - type: if
                              if:
                                type: is-sprinting
                              then:
                                - type: remove-attribute-modifier
                                  attribute-modifiers:
                                    - attribute: movement_speed
                                      name: boots_of_haste
                                      amount: 0.3
                                      operation: ADD_SCALAR
                                - type: add-attribute-modifier
                                  attribute-modifiers:
                                    - attribute: movement_speed
                                      name: boots_of_haste
                                      amount: 0.5
                                      operation: ADD_SCALAR
  unsprint:
    - type: remove-attribute-modifier
      attribute-modifiers:
        - attribute: movement_speed
          name: boots_of_haste
          amount: 0.5
          operation: ADD_SCALAR
  sneak:
    - type: remove-attribute-modifier
      attribute-modifiers:
        - attribute: movement_speed
          name: boots_of_haste
          amount: 0.5
          operation: ADD_SCALAR
