version: 1
name: "<transition:#44c94f:#1b9125>Climbing Gloves"
item: leather
custom-model-data: 4
model: "blanktopia:rares/climbing_gloves"
enchantments:
  blanktopia:soulbound: 1
enchantment-glint: false
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Allows you to jump off walls'
  - '<white>by pressing <aqua>sneak<white> when'
  - '<white>against a wall.'
  - ''
  - '<grey>Slot: <#ff4e1d>Trinket'
slots:
  - TRINKET
triggers:
  equip-armor:
    - type: add-permission
      permissions:
        - walljump.use
  unequip-armor:
    - type: remove-permission
      permissions:
        - walljump.use
