version: 1

name: "&#d580fc-#ffbf0d&Horn of Plenty"
material: BOWL
custom-model-data: 1
model: "blanktopia:rares/horn_of_plenty"

soulbound: true
unenchantable: true
unique: true

lore: |-

  &fAutomatically refills your
  &fhunger, but keeps your
  &fsaturation low.

  &7Slot: &#ff4e1d&Trinket

slots:
- TRINKET

triggers:
  tick-slow:
  - type: set-hunger
    hunger: 19
  equip-armor:
  - type: set-hunger
    hunger: 19
