version: 1
name: "<transition:#d580fc:#ffbf0d>Horn of Plenty"
material: BOWL
custom-model-data: 1
model: "blanktopia:rares/horn_of_plenty"
soulbound: true
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Automatically refills your'
  - '<white>hunger, but keeps your'
  - '<white>saturation low.'
  - ''
  - '<grey>Slot: <#ff4e1d>&Trinket'
slots:
  - TRINKET
triggers:
  tick-slow:
    - type: set-hunger
      hunger: 19
  equip-armor:
    - type: set-hunger
      hunger: 19
