version: 1
name: "<transition:#d580fc:#ffbf0d>Horn of Plenty"
item: bowl
custom-model-data: 1
model: "blanktopia:rares/horn_of_plenty"
enchantments:
  blanktopia:soulbound: 1
enchantment-glint: false
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Automatically refills your'
  - '<white>hunger when low.'
  - ''
  - '<grey>Slot: <#ff4e1d>Trinket'
slots:
  - TRINKET
triggers:
  tick-slow:
    - type: if
      if:
        type: hunger
        hunger: 19
        comparison: <
      then:
        - type: set-hunger
          hunger: 19
  equip-armor:
    - type: if
      if:
        type: hunger
        hunger: 19
        comparison: <
      then:
        - type: set-hunger
          hunger: 19
