version: 2
name: "<transition:#f76c9d:#b5f9cb>Hummingbird"
item: feather
custom-model-data: 1
model: "blanktopia:rares/hummingbird"
soulbound: true
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Allows you to hover in claims'
  - '<white>you are <bold>/trusted</bold><white> in.'
  - ''
  - '<grey>Slot: <#ff4e1d>Trinket'
slots:
  - TRINKET
triggers:
  equip-armor:
    - type: fly-in-claims
      fly: true
  unequip-armor:
    - type: fly-in-claims
      fly: false
#   tick-slow:
#     - type: if
#       if:
#         type: is-flying
#       then:
#         - type: spawn-particle
#           count: 1
#           y: 0.9
#           offset-x: 0.3
#           offset-y: 0.6
#           offset-z: 0.3
#           particle: FALLING_DUST
#           block: PEARLESCENT_FROGLIGHT
