version: 2
name: "<transition:#f7fc92:#fccf8a>Miner's Helmet"
item: glowstone_dust
custom-model-data: 1
model: "blanktopia:hats/miners_helmet"
enchantments:
  blanktopia:soulbound: 1
enchantment-glint: false
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Grants you <grey>Haste II<white>.'
  - ''
  - '<grey>Slot: <#ff4e1d>Trinket'
slots:
  - HEAD
  - TRINKET
triggers:
  equip-armor:
    - type: add-permanent-potion-effect
      key: miners-helmet
      effects: {fast_digging: 1}
  unequip-armor:
    - type: remove-permanent-potion-effect
      key: miners-helmet
