name: "&#ffd747&Miner's Helmet"
material: GLOWSTONE_DUST
custom-model-data: 1

version: 1

lore: |-
  &8-------------------------
  &7Slot: &#ff4e1d&Trinket
  
  &fGrants you &7Haste II&f.
  
  &8-------------------------
  &6MINER's Crate Item

unbreakable: true

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1

slots:
- TRINKET

triggers:
  equip-armor:
  - type: add-permanent-potion-effect
    key: miners-helmet
    effects: { fast_digging: 1 }
  unequip-armor:
  - type: remove-permanent-potion-effect
    key: miners-helmet
