version: 1
name: "<transition:#41a65c:#91cc5e>Minish Cap"
item: paper
# custom-model-data: 2
# model: "blanktopia:rares/ambrosia"
soulbound: true
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Makes you tiny.'
  - ''
  - '<grey>Slot: <#ff4e1d>Trinket'
slots:
  - TRINKET
triggers:
  equip-armor:
    - type: add-attribute-modifier
      attribute-modifiers:
        - attribute: scale
          name: minish_cap
          amount: -0.7
          operation: MULTIPLY_SCALAR_1
    - type: add-attribute-modifier
      attribute-modifiers:
        - attribute: movement_speed
          name: minish_cap
          amount: -0.5
          operation: MULTIPLY_SCALAR_1
    - type: add-attribute-modifier
      attribute-modifiers:
        - attribute: step_height
          name: minish_cap
          amount: -0.5
          operation: MULTIPLY_SCALAR_1
    - type: add-attribute-modifier
      attribute-modifiers:
        - attribute: jump_strength
          name: minish_cap
          amount: -0.4
          operation: MULTIPLY_SCALAR_1
  unequip-armor:
    - type: remove-attribute-modifier
      attribute-modifiers:
        - attribute: scale
          name: minish_cap
          amount: -0.7
          operation: MULTIPLY_SCALAR_1
    - type: remove-attribute-modifier
      attribute-modifiers:
        - attribute: movement_speed
          name: minish_cap
          amount: -0.5
          operation: MULTIPLY_SCALAR_1
    - type: remove-attribute-modifier
      attribute-modifiers:
        - attribute: step_height
          name: minish_cap
          amount: -0.5
          operation: MULTIPLY_SCALAR_1
    - type: remove-attribute-modifier
      attribute-modifiers:
        - attribute: jump_strength
          name: minish_cap
          amount: -0.4
          operation: MULTIPLY_SCALAR_1
