name: "&#f9c1ae-#f9e7e0&Parachute"
material: FEATHER
custom-model-data: 2

unique: true

lore: |-
  &8-------------------------
  &7Slot: &#ff4e1d&Trinket
  
  &fGrants immunity to fall
  &fdamage.
  
  &8-------------------------
  &6EXPLORER's Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1

slots:
- TRINKET

triggers:
  damaged:
  - type: immunity
    causes: [FALL]
