version: 1
name: "<transition:#f9c1ae:#f9e7e0>Parachute"
material: FEATHER
custom-model-data: 2
model: "blanktopia:rares/parachute"
soulbound: true
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Grants immunity to fall'
  - '<white>damage.'
  - ''
  - '<grey>Slot: <#ff4e1d>&Trinket'
slots:
  - TRINKET
triggers:
  damaged:
    - type: immunity
      causes: [FALL]
