version: 1

name: "&#89c4c0-#d2e8e8&Pathfinder's Grappling Hook"
material: WOODEN_HOE
custom-model-data: 1009
model: "blanktopia:rares/grappling_hook"

unique: true
unbreakable: true

lore: |-
  &8-------------------------
  &7Slot: &#ff4e1d&Trinket

  &fAllows you to fire a grappling
  &fhook by pressing &bF&f.
  &fPress &bSneak&f to release.
  
  &7Range: 50 blocks
  &7Speed: Fast
  &8-------------------------
  &6EXPLORER's Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1

slots:
- TRINKET

triggers:
  right-click:
  - type: launch-grapple
    speed: 5.0
  - type: cancel
  swap-hand:
  - type: launch-grapple
    speed: 5.0
  - type: cancel
  projectile-tick:
  - type: grapple-tick
    acceleration: 1.0
    max-speed: 1.0
    detach-speed: 0.5
    range: 50
    particle: SOUL_FIRE_FLAME
