version: 2
name: "<transition:#ff730f:#ffca2d>Ra's Protection"
item: gold_nugget
custom-model-data: 1
model: "blanktopia:rares/ras_protection"
enchantments:
  blanktopia:soulbound: 1
enchantment-glint: false
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Grants immunity to fire and'
  - '<white>lava.'
  - ''
  - '<grey>Slot: <#ff4e1d>Trinket'
slots:
  - TRINKET
triggers:
  equip-armor:
    - type: add-permanent-potion-effect
      key: ras-protection
      effects: {fire_resistance: 0}
  unequip-armor:
    - type: remove-permanent-potion-effect
      key: ras-protection
  damaged:
    - type: immunity
      causes: [LAVA, FIRE, FIRE_TICK]
