version: 1

name: "&#ff730f-#ffca2d&Ra's Protection"
material: GOLD_NUGGET
custom-model-data: 1

unique: true

lore: |-
  &8-------------------------
  &7Slot: &#ff4e1d&Trinket
  
  &fGrants immunity to fire and
  &flava.
  
  &8-------------------------
  &6MINER's Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1

slots:
- TRINKET

triggers:
  equip-armor:
  - type: add-permanent-potion-effect
    key: ras-protection
    effects: { fire_resistance: 0 }
  unequip-armor:
  - type: remove-permanent-potion-effect
    key: ras-protection
  damaged:
  - type: immunity
    causes: [LAVA, FIRE, FIRE_TICK]
