version: 2

name: "&#fff0c1-#c1f6ff&Sandy's Helmet"
material: WHITE_STAINED_GLASS

soulbound: true
unenchantable: true
unique: true

lore: |-

  &fAllows you to breathe
  &funderwater.
  
  &7Slot: &#ff4e1d&Trinket

slots:
- TRINKET

triggers:
  equip-armor:
  - type: add-permanent-potion-effect
    key: sandys-helmet
    effects: { water_breathing: 0 }
  unequip-armor:
  - type: remove-permanent-potion-effect
    key: sandys-helmet
  right-click:
  - type: cancel
