pages:
- |-
  [Blanktopia](color=#486aa8 bold) [Build](color=#86a8e7 bold) [Friendly Reminder](color=#486aa8 bold)
  [------------](color=#486aa8 bold)

  [Please look around your build site and try to keep at least 100 blocks away from other players' creations.](color=#486aa8)

  [Thanks for being a considerate builder!](color=#486aa8)