version: 3
name: '<transition:#8db360:#056621>Biome Wand'
material: WOODEN_HOE
custom-model-data: 1
model: "blanktopia:rares/biome_wand"
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<aqua>Left-click<white> to select a'
  - '<white>biome.'
  - '<aqua>Right-click<white> to turn an area'
  - '<white>into the selected biome.'
triggers:
  right-click:
    - type: if
      if:
        type: raycast
        range: 20
        actions:
          - type: biome-wand
            range: 3
      then:
        - type: item-cooldown
          ticks: 5
    - type: cancel
  left-click:
    - type: biome-wand-pick
    - type: cancel
