version: 2

name: '&#8db360-#056621&Biome Wand'
material: WOODEN_HOE
custom-model-data: 1
model: "blanktopia:rares/biome_wand"

unbreakable: true

lore: |-
  &8-------------------------

  &bLeft-click&f to select a
  &fbiome.
  &bRight-click&f to turn an area
  &finto the selected biome.

  &8-------------------------
  &6NATURE Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1

triggers:
  right-click:
    - type: if
      if:
        type: raycast
        range: 20
        actions:
        - type: biome-wand
          range: 3
      then:
      - type: item-cooldown
        ticks: 5
    - type: cancel
  left-click:
    - type: biome-wand-pick
    - type: cancel
