version: 2
name: "<transition:#a46bff:#fa6bff>Block Zapper"
item: wooden_hoe
custom-model-data: 1005
model: "minecraft:item/popped_chorus_fruit"
enchantments:
  blanktopia:soulbound: 1
enchantment-glint: false
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<aqua>Left-click<white> to select a'
  - '<white>material to replace with.'
  - '<aqua>Right-click<white> to replace a'
  - '<white>block with the material.'
triggers:
  left-click:
    - type: raycast
      range: 20
      actions:
        - type: select-material
    - type: cancel
  right-click:
    - type: if
      if:
        type: item-cooldown
      then:
        - type: if
          if:
            type: raycast
            range: 20
            actions:
              - type: replace-block
          then:
            - type: item-cooldown
              ticks: 1
    - type: cancel
