version: 2

name: "&#a46bff-#fa6bff&Block Zapper"
material: WOODEN_HOE
custom-model-data: 1005
model: "minecraft:item/popped_chorus_fruit"

soulbound: true
unbreakable: true
unenchantable: true
unique: true

lore: |-

  &bLeft-click&f to select a
  &fmaterial to replace with.
  &bRight-click&f to replace a
  &fblock with the material.

triggers:
  left-click:
  - type: raycast
    range: 20
    actions:
    - type: select-material
  - type: cancel
  right-click:
  - type: if
    if:
      type: item-cooldown
    then:
    - type: if
      if:
        type: raycast
        range: 20
        actions:
        - type: replace-block
      then:
      - type: item-cooldown
        ticks: 1
  - type: cancel
