version: 1
name: "<transition:#3b875c:#8ec153>Botanic Manipulator"
item: wooden_hoe
custom-model-data: 1010
model: "blanktopia:rares/biome_wand"
enchantments:
  blanktopia:soulbound: 1
enchantment-glint: false
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<aqua>Right-click<white> to cycle a'
  - '<white>block''s variation.'
  - ''
  - '<white>Works on:'
  - '<dark_grey>- <white>Wood'
  - '<dark_grey>- <white>Flowers'
  - '<dark_grey>- <white>Mushrooms'
triggers:
  right-click-block:
    - type: cycle-flora
    - type: cancel
  left-click-block:
    - type: cycle-flora
      reversed: true
    - type: cancel
