name: "&#ffa5ee-#b6a5ff&Builder's Wand"
material: WOODEN_HOE
custom-model-data: 1003

unique: true
unbreakable: true

lore: |-
  &8-------------------------
  
  &bRight-click&f on a block
  &fto place blocks in a &b7x7&f
  &farea. Requires the block to
  &fbe in your inventory.
  
  &8-------------------------
  &6BUILDER's Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1

triggers:
  tick-slow:
  - type: raycast
    range: 20
    actions:
    - type: builders-wand-highlight
      color: 0x64001000
      range: 3
  right-click:
  - type: if
    if:
      type: all
      actions:
      - type: item-cooldown
    then:
    - type: if
      if: 
        type: raycast
        range: 20
        actions:
        - type: builders-wand
          range: 3
      then:
      - type: item-cooldown
        ticks: 1
    - type: raycast
      range: 20
      actions:
      - type: clear-highlight
      - type: builders-wand-highlight
        color: 0x64001000
        range: 3
    - type: cancel
