alias: pokeball
name: "<blue>Doraemon's Pocket"
item: ender_chest
lore:
  - ''
  - '<aqua>Right-click<white> from your'
  - '<white>inventory to access your'
  - '<white>ender chest.'
enchantments:
  blanktopia:soulbound: 1
enchantment-glint: false
unbreakable: true
unenchantable: true
unique: true
triggers:
  place-block:
    - type: cancel
  drop:
    - type: cancel
  right-click:
    - type: sudo-command
      command: enderchest
      permissions:
        - essentials.enderchest
    - type: play-sound
      sound: block.ender_chest.open
    - type: cancel
  right-click-inventory:
    - type: sudo-command
      command: enderchest
      permissions:
        - essentials.enderchest
    - type: play-sound
      sound: block.ender_chest.open
    - type: cancel
