name: "&9Doraemon's Pocket"
material: ENDER_CHEST

lore: |-
  &8-------------------------
  
  &bRight-click&f from your
  &finventory to access your
  &fender chest.
  
  &8-------------------------
  &6INFINITY Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1
  infinity: 1

triggers:
  place-block:
  - type: cancel
  drop:
  - type: cancel
  right-click:
  - type: sudo-command
    command: enderchest
    permissions:
    - essentials.enderchest
  - type: play-sound
    sound: block.ender_chest.open
  - type: cancel
  right-click-inventory:
  - type: sudo-command
    command: enderchest
    permissions:
    - essentials.enderchest
  - type: play-sound
    sound: block.ender_chest.open
  - type: cancel
