version: 1
name: "<transition:#b1cde3:#afa7d9>Everstone"
material: ENDER_EYE
custom-model-data: 1
model: "blanktopia:rares/everstone"
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<aqua>Right-click<white> an animal'
  - '<white>to stop it from growing.'
triggers:
  right-click:
    - type: everstone
    - type: cancel
