version: 3
name: "&#e71e02-#ffd729&Hellfire"
material: WOODEN_HOE
custom-model-data: 1007
model: "minecraft:item/lava_bucket"
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '&fInfinite lava bucket.'
enchantments:
  infinity: 1
triggers:
  right-click:
    - type: lava-bucket
    - type: cancel
