version: 3
name: "<transition:#e71e02:#ffd729>Hellfire"
item: wooden_hoe
custom-model-data: 1007
model: "minecraft:item/lava_bucket"
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Infinite lava bucket.'
enchantments:
  blanktopia:soulbound: 1
  infinity: 1
triggers:
  right-click:
    - type: lava-bucket
    - type: cancel
