name: "&#e71e02-#ffd729&Hellfire"
material: WOODEN_HOE
custom-model-data: 1007
model: "minecraft:item/lava_bucket"

unique: true
unbreakable: true

version: 1

lore: |-
  &8-------------------------
  
  &fInfinite lava bucket.
  
  &8-------------------------
  &6INFINITY Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1
  infinity: 1

triggers:
  right-click:
  - type: lava-bucket
  - type: cancel
