name: "&fLumos&e ☀"
material: WOODEN_HOE
custom-model-data: 1000

unbreakable: true

lore: |-
  &8-------------------------
  
  &fNever be afraid of the dark
  &fagain!
  
  &8-------------------------
  &6INFINITY's Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1
  infinity: 1

triggers:
  tick-slow:
  - type: raycast
    range: 20
    actions:
    - type: highlight-block
      color: 0x64001000
  right-click:
  - type: if
    if:
      type: item-cooldown
    then:
    - type: if
      if:
        type: raycast
        range: 20
        actions:
        - type: light
      then:
      - type: item-cooldown
        ticks: 5
  - type: cancel
  left-click:
  - type: if
    if:
      type: item-cooldown
    then:
    - type: if
      if:
        type: raycast
        range: 20
        actions:
        - type: remove-light
          range: 3
      then:
      - type: item-cooldown
        ticks: 5
  - type: cancel
