name: "&#fffcdb-#ffc272&Lumos"
material: WOODEN_HOE
custom-model-data: 1000

unique: true
unbreakable: true

lore: |-
  &8-------------------------
  
  &bRight-click&f to place an
  &finvisible light source.
  &bLeft-click&f to remove nearby
  &flights.
  
  &8-------------------------
  &6INFINITY's Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1
  infinity: 1

triggers:
  right-click:
  - type: if
    if:
      type: item-cooldown
    then:
    - type: if
      if:
        type: raycast
        range: 20
        actions:
        - type: light
      then:
      - type: item-cooldown
        ticks: 5
  - type: cancel
  left-click:
  - type: if
    if:
      type: item-cooldown
    then:
    - type: if
      if:
        type: raycast
        range: 20
        actions:
        - type: remove-light
          range: 3
      then:
      - type: item-cooldown
        ticks: 5
  - type: cancel
