version: 1
name: "<transition:#fffcdb:#ffc272>Lumos"
material: WOODEN_HOE
custom-model-data: 1000
model: "blanktopia:rares/lumos"
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<aqua>Right-click<white> to place an'
  - '<white>invisible light source.'
  - '<aqua>Left-click<white> to remove nearby'
  - '<white>lights.'
enchantments:
  infinity: 1
triggers:
  right-click:
    - type: if
      if:
        type: item-cooldown
      then:
        - type: if
          if:
            type: raycast
            range: 20
            actions:
              - type: light
          then:
            - type: item-cooldown
              ticks: 5
    - type: cancel
  left-click:
    - type: if
      if:
        type: item-cooldown
      then:
        - type: if
          if:
            type: raycast
            range: 20
            actions:
              - type: remove-light
                range: 3
          then:
            - type: item-cooldown
              ticks: 5
    - type: cancel
