version: 2
name: "<transition:#6bffb5:#6bfff7>Measuring Tape"
item: wooden_hoe
custom-model-data: 1004
model: "blanktopia:rares/measuring_tape"
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<aqua>Left-click<white> to set a'
  - '<white>point to measure from.'
  - '<aqua>Right-click<white> to measure the'
  - '<white>length between two blocks.'
triggers:
  tick-slow:
    - type: measure-distance-tick
  left-click:
    - type: raycast
      range: 20
      actions:
        - type: measure-distance
          is-origin: true
    - type: cancel
  right-click:
    - type: raycast
      range: 20
      actions:
        - type: measure-distance
    - type: cancel
