version: 1

name: "&#6bffb5-#6bfff7&Measuring Tape"
material: WOODEN_HOE
custom-model-data: 1004
model: "minecraft:item/string"

unique: true
unbreakable: true

lore: |-
  §8-------------------------
  
  §bLeft-click§f to set a
  §fpoint to measure from.
  §bRight-click§f to measure the
  §flength between two blocks.
  
  §8-------------------------
  §6BUILDER's Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1

triggers:
  tick-slow:
  - type: measure-distance-tick
  left-click:
  - type: raycast
    range: 20
    actions:
    - type: measure-distance
      is-origin: true
  - type: cancel
  right-click:
  - type: raycast
    range: 20
    actions:
    - type: measure-distance
  - type: cancel
