version: 3
name: "<transition:#45b6f7:#c9e7ff>Nile Water"
item: wooden_hoe
custom-model-data: 1006
model: "minecraft:item/water_bucket"
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Infinite water bucket.'
enchantments:
  blanktopia:soulbound: 1
  infinity: 1
triggers:
  right-click:
    - type: water-bucket
    - type: cancel
