name: "&#45b6f7-#c9e7ff&Nile Water"
material: WOODEN_HOE
custom-model-data: 1006

unbreakable: true

version: 1

lore: |-
  &8-------------------------
  
  &fInfinite water bucket.
  
  &8-------------------------
  &6INFINITY Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1
  infinity: 1

triggers:
  right-click:
  - type: water-bucket
  - type: cancel
