version: 0
name: "<transition:#8f7c71:#87635d>Packing Tape"
item: slime_ball
custom-model-data: 1
model: "blanktopia:rares/packing_tape"
enchantments:
  blanktopia:soulbound: 1
enchantment-glint: false
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<aqua>Sneak right-click<white> to'
  - '<white>pick up a chest with all'
  - '<white>its contents.'
triggers:
  right-click-block:
    - type: packing-tape
    - type: cancel
