version: 1

name: "&rainbow&Paint Brush"
material: WOODEN_HOE
custom-model-data: 1001
model: "blanktopia:rares/paint_brush"

unique: true
unbreakable: true

lore: |-
  &7Paint: NONE
  &8-------------------------
  
  &bLeft-click&f to pick a colour.
  &bRight-click&f to paint blocks.
  
  &fWorks on:
  &8- &fGlass
  &8- &fWool
  &8- &fTerracotta
  &8- &fConcrete
  
  &8-------------------------
  &6BUILDER's Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1

triggers:
#  tick:
#  - type: raycast
#    range: 20
#    actions:
#    - type: paint-brush-highlight
#      range: 2
#      duration: 50
  left-click:
  - type: raycast
    range: 20
    actions:
    - type: paint-brush-pick
  - type: cancel
  right-click:
  - type: raycast
    range: 20
    actions:
    - type: if
      if:
        type: is-sneaking
      then:
      - type: paint-brush-paint
        range: 0
      else:
      - type: paint-brush-paint
        range: 2
  - type: cancel
  right-click-entity:
  - type: cancel
