version: 2
name: "ainbow&Paint Brush"
material: WOODEN_HOE
custom-model-data: 1001
model: "blanktopia:rares/paint_brush"
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<grey>Paint: NONE'
  - ''
  - '<aqua>Left-click<white> to pick a colour.'
  - '<aqua>Right-click<white> to paint blocks.'
  - ''
  - '<white>Works on:'
  - '<dark_grey>- <white>Glass'
  - '<dark_grey>- <white>Wool'
  - '<dark_grey>- <white>Terracotta'
  - '<dark_grey>- <white>Concrete'
triggers:
  left-click:
    - type: raycast
      range: 20
      actions:
        - type: paint-brush-pick
    - type: cancel
  right-click:
    - type: raycast
      range: 20
      actions:
        - type: if
          if:
            type: is-sneaking
          then:
            - type: paint-brush-paint
              range: 0
          else:
            - type: paint-brush-paint
              range: 2
    - type: cancel
  right-click-entity:
    - type: cancel
