version: 0
name: "<transition:#fffcdb:#ffc272>Pocket Sponge"
item: sponge
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<aqua>Right-click<white> to remove'
  - '<white>water and lava like a sponge'
triggers:
  place-block:
    - type: cancel
  right-click:
    - type: if
      if:
        type: item-cooldown
      then:
        - type: if
          if:
            type: sponge
            range: 2
          then:
            - type: item-cooldown
              ticks: 5
    - type: cancel
