version: 0
name: "&#fffcdb-#ffc272&Pocket Sponge"
material: SPONGE
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '&bRight-click&f to remove'
  - '&fwater and lava like a sponge'
triggers:
  place-block:
    - type: cancel
  right-click:
    - type: if
      if:
        type: item-cooldown
      then:
        - type: if
          if:
            type: sponge
            range: 2
          then:
            - type: item-cooldown
              ticks: 5
    - type: cancel
