version: 0

name: "&#f00000-#ffffff&Pokeball"
material: ENDER_EYE
custom-model-data: 2
model: "blanktopia:rares/pokeball"

soulbound: true
unbreakable: true
unenchantable: true
unique: true

lore: |-

  &bRight-click&f to store an
  &fentity in the ball.

  &bRight-click&f again to 
  &frelease it.

triggers:
  right-click:
  - type: pokeball
  - type: cancel
