version: 0
name: "<transition:#f00000:#ffffff>Pokeball"
material: ENDER_EYE
custom-model-data: 2
model: "blanktopia:rares/pokeball"
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<aqua>Right-click<white> to store an'
  - '<white>entity in the ball.'
  - ''
  - '<aqua>Right-click<white> again to '
  - '<white>release it.'
triggers:
  right-click:
    - type: pokeball
    - type: cancel
