alias: packing-tape
name: "<#33d8f2>Portable Ore Compactor ⏹"
material: NETHER_STAR
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<aqua>Right-click<white> from your'
  - '<white>inventory to compact items'
  - '<white>into blocks.'
triggers:
  right-click:
    - type: sudo-command
      command: condense inventory
      permissions:
        - essentials.condense
    - type: play-sound
      sound: block.beacon.power.select
      pitch: 2
    - type: cancel
  right-click-inventory:
    - type: sudo-command
      command: condense
      permissions:
        - essentials.condense
    - type: play-sound
      sound: block.beacon.power.select
      pitch: 2
    - type: cancel
