name: "&x&3&3&8&7&6&dPortable Trash Can ⏹"
material: STRIPPED_WARPED_HYPHAE

lore: |-
  &8-------------------------
  
  &bRight-click&f from your
  &finventory to open a
  &fportable trash can.
  
  &8-------------------------
  &6MINER's Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1

triggers:
  right-click:
  - type: sudo-command
    command: disposal
    permissions:
    - essentials.disposal
  - type: play-sound
    sound: block.shulker_box.open
    pitch: 0.8
  - type: cancel
  right-click-inventory:
  - type: sudo-command
    command: disposal
    permissions:
    - essentials.disposal
  - type: play-sound
    sound: block.shulker_box.open
    pitch: 0.8
  - type: cancel
