alias: packing-tape
name: "<#33876d>Portable Trash Can ⏹"
material: STRIPPED_WARPED_HYPHAE
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<aqua>Right-click<white> from your'
  - '<white>inventory to open a'
  - '<white>portable trash can.'
triggers:
  right-click:
    - type: sudo-command
      command: disposal
      permissions:
        - essentials.disposal
    - type: play-sound
      sound: block.shulker_box.open
      pitch: 0.8
    - type: cancel
  right-click-inventory:
    - type: sudo-command
      command: disposal
      permissions:
        - essentials.disposal
    - type: play-sound
      sound: block.shulker_box.open
      pitch: 0.8
    - type: cancel
