name: "&#1ce0ea&Wrench"
material: WOODEN_HOE
custom-model-data: 1002

unique: true
unbreakable: true

lore: |-
  &8-------------------------
  
  &bRight-click&f to rotate a block
  &for turn an item frame
  &finvisible.

  &8-------------------------
  &6BUILDER's Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1

triggers:
  right-click-block:
  - type: rotate
  - type: cancel
  left-click-block:
  - type: rotate
    reversed: true
  - type: cancel
  right-click-entity:
  - type: if
    if:
      type: toggle-item-frame-visibility
    then:
    - type: cancel
