version: 1
name: "<transition:#adb0b8:#7e8596>Wrench"
item: wooden_hoe
custom-model-data: 1002
model: "blanktopia:rares/wrench"
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<aqua>Right-click<white> to rotate a block'
  - '<white>or turn an item frame'
  - '<white>invisible.'
triggers:
  right-click-block:
    - type: rotate
    - type: cancel
  left-click-block:
    - type: rotate
      reversed: true
    - type: cancel
  right-click-entity:
    - type: if
      if:
        type: toggle-item-frame-visibility
      then:
        - type: cancel
