name: "&#ea4f4f-#fff56d&Rocket Boots"
material: FIREWORK_ROCKET
custom-model-data: 1

unique: true

lore: |-
  &8-------------------------
  &7Slot: &#ff4e1d&Trinket

  &eJump&f while &esneaking&f to
  &fshoot up like a rocket!

  &8-------------------------
  &6EXPLORER's Crate Item

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1

slots:
- TRINKET

triggers:
  sneak:
  - type: add-permanent-potion-effect
    key: rocket-boots
    effects: { jump: 5 }
  unsneak:
  - type: remove-permanent-potion-effect
    key: rocket-boots
  jump:
  - type: if
    if:
      type: is-sneaking
    then:
    - type: repeat
      count: 3
      interval: 2
      actions:
      - type: spawn-particle
        count: 2
        offset-x: 0.3
        offset-y: 0.3
        offset-z: 0.3
        particle: FIREWORK
      - type: spawn-particle
        count: 2
        offset-x: 0.3
        offset-y: 0.3
        offset-z: 0.3
        particle: FLAME
    - type: play-sound
      pitch: 1.1
      sound: entity.firework_rocket.launch
      volume: 0.5
