version: 4

name: "&#eba5ff-#c800fa&Anti-Gravity Bow"
material: BOW
custom-model-data: 1
model: "blanktopia:rares/anti_gravity_bow"
models:
  - material: BOW
    predicate: { custom_model_data: 1, pulling: 1 }
    model: "blanktopia:rares/anti_gravity_bow_pulling_0"
  - material: BOW
    predicate: { custom_model_data: 1, pulling: 1, pull: 0.65 }
    model: "blanktopia:rares/anti_gravity_bow_pulling_1"
  - material: BOW
    predicate: { custom_model_data: 1, pulling: 1, pull: 0.9 }
    model: "blanktopia:rares/anti_gravity_bow_pulling_2"

soulbound: true
unbreakable: true
unenchantable: true
unique: true

lore: |-
  
  &fArrows fly in a straight line.
  &fInflicts &bLevitation&f on targets.

enchantments:
  infinity: 1
  power: 5


triggers:
  projectile-launch:
  - type: arrow-color
    color: "de7afa"
  - type: projectile-gravity
    gravity: false
  projectile-hit:
  - type: null-player
  - type: add-potion-effect
    effect: levitation
    duration: 80
    level: 1
