version: 4
name: "<transition:#eba5ff:#c800fa>Anti-Gravity Bow"
item: bow
custom-model-data: 1
custom-model: {
    "type": "minecraft:range_dispatch",
    "entries": [
      {
        "model": {
          "type": "minecraft:model",
          "model": "blanktopia:rares/anti_gravity_bow_pulling_0"
        },
        "threshold": 1
      },
      {
        "model": {
          "type": "minecraft:model",
          "model": "blanktopia:rares/anti_gravity_bow_pulling_1"
        },
        "threshold": 13
      },
      {
        "model": {
          "type": "minecraft:model",
          "model": "blanktopia:rares/anti_gravity_bow_pulling_2"
        },
        "threshold": 18
      }
    ],
    "property": "minecraft:use_duration",
    "fallback": {
      "type": "minecraft:model",
      "model": "blanktopia:rares/anti_gravity_bow"
    }
  }
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Arrows fly in a straight line.'
  - '<white>Inflicts <aqua>Levitation<white> on targets.'
enchantments:
  blanktopia:soulbound: 1
  infinity: 1
  power: 5
triggers:
  projectile-launch:
    - type: arrow-color
      color: "de7afa"
    - type: projectile-gravity
      gravity: false
  projectile-hit:
    - type: null-player
    - type: add-potion-effect
      effect: levitation
      duration: 80
      level: 1
