name: "&#ef4faa-#ef4f61&Chu Ko Nu"
material: CROSSBOW
custom-model-data: 1
model: "blanktopia:rares/chu_ko_nu"
models:
  - material: CROSSBOW
    predicate: { custom_model_data: 1, pulling: 1 }
    model: "blanktopia:rares/chu_ko_nu_pulling_0"
  - material: CROSSBOW
    predicate: { custom_model_data: 1, pulling: 2 }
    model: "blanktopia:rares/chu_ko_nu_pulling_1"
  - material: CROSSBOW
    predicate: { custom_model_data: 1, pulling: 3 }
    model: "blanktopia:rares/chu_ko_nu_pulling_2"
  - material: CROSSBOW
    predicate: { custom_model_data: 1, charged: 1 }
    model: "blanktopia:rares/chu_ko_nu_arrow"
  - material: CROSSBOW
    predicate: { custom_model_data: 1, charged: 1, firework: 1 }
    model: "blanktopia:rares/chu_ko_nu_firework"

unique: true

lore: |-
  §8-------------------------
  
  §fFires 5 arrows per volley.
  
  §8-------------------------
  §6EXPLORER's Crate Item

unbreakable: true

enchantments:
  blanktopia:soulbound: 1
  infinity: 1
  quick_charge: 1

triggers:
  projectile-launch:
  - type: arrow-volley
    count: 5
    delay: 2
  projectile-hit:
  - type: delay
    ticks: 1
    actions:
    - type: null-player
    - type: set-no-damage-tick
      ticks: 0
