version: 1
name: "<transition:#ef4faa:#ef4f61>Chu Ko Nu"
item: crossbow
custom-model-data: 1
custom-model: {
    "type": "minecraft:condition",
    "on_false": {
      "type": "minecraft:select",
      "cases": [
        {
          "model": {
            "type": "minecraft:model",
            "model": "blanktopia:rares/chu_ko_nu_arrow"
          },
          "when": "arrow"
        },
        {
          "model": {
            "type": "minecraft:model",
            "model": "blanktopia:rares/chu_ko_nu_firework"
          },
          "when": "rocket"
        }
      ],
      "fallback": {
        "type": "minecraft:model",
        "model": "blanktopia:rares/chu_ko_nu"
      },
      "property": "minecraft:charge_type"
    },
    "on_true": {
      "type": "minecraft:range_dispatch",
      "entries": [
        {
          "model": {
            "type": "minecraft:model",
            "model": "blanktopia:rares/chu_ko_nu_pulling_1"
          },
          "threshold": 0.58
        },
        {
          "model": {
            "type": "minecraft:model",
            "model": "blanktopia:rares/chu_ko_nu_pulling_2"
          },
          "threshold": 1.0
        }
      ],
      "fallback": {
        "type": "minecraft:model",
        "model": "blanktopia:rares/chu_ko_nu_pulling_0"
      },
      "property": "minecraft:crossbow/pull"
    },
    "property": "minecraft:using_item"
  }
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Fires 5 arrows per volley.'
enchantments:
  blanktopia:soulbound: 1
  infinity: 1
  quick_charge: 3
triggers:
  projectile-launch:
    - type: arrow-volley
      count: 5
      delay: 2
  projectile-hit:
    - type: delay
      ticks: 1
      actions:
        - type: null-player
        - type: set-no-damage-tick
          ticks: 0
