version: 1
name: "<transition:#ef4faa:#ef4f61>Chu Ko Nu"
item: crossbow
custom-model-data: 1
model: "blanktopia:rares/chu_ko_nu"
models:
  - item: crossbow
    predicate: {custom_model_data: 1, pulling: 1}
    model: "blanktopia:rares/chu_ko_nu_pulling_0"
  - item: crossbow
    predicate: {custom_model_data: 1, pulling: 2}
    model: "blanktopia:rares/chu_ko_nu_pulling_1"
  - item: crossbow
    predicate: {custom_model_data: 1, pulling: 3}
    model: "blanktopia:rares/chu_ko_nu_pulling_2"
  - item: crossbow
    predicate: {custom_model_data: 1, charged: 1}
    model: "blanktopia:rares/chu_ko_nu_arrow"
  - item: crossbow
    predicate: {custom_model_data: 1, charged: 1, firework: 1}
    model: "blanktopia:rares/chu_ko_nu_firework"
soulbound: true
unbreakable: true
unenchantable: true
unique: true
lore:
  - ''
  - '<white>Fires 5 arrows per volley.'
enchantments:
  infinity: 1
  quick_charge: 3
triggers:
  projectile-launch:
    - type: arrow-volley
      count: 5
      delay: 2
  projectile-hit:
    - type: delay
      ticks: 1
      actions:
        - type: null-player
        - type: set-no-damage-tick
          ticks: 0
