version: 2

name: "&#5b577f-#4a217c&Venom"
material: NETHERITE_SWORD
custom-model-data: 1

unique: true

lore: |-
  &7Poison Immunity
  &8-------------------------

  &fUnleashs poisonous fangs.

  &8-------------------------
  &6EXPLORER's Crate Item

unbreakable: true

enchantments:
  sharpness: 7
  sweeping_edge: 3
  looting: 4
  blanktopia:sting: 3
  blanktopia:final: 1
  blanktopia:soulbound: 1

slots: [HAND, OFF_HAND]

triggers:
  damaged:
  - type: immunity
    causes: [POISON]

  left-click-block:
  - type: if
    if:
      type: attack-cooldown
    then:
    - type: evoker-fang
      location:
        type: block

  damage-entity:
  - type: if
    if:
      type: attack-cooldown
    then:
    - type: evoker-fang
