version: 3
name: "<transition:#5b577f:#4a217c>Venom"
item: netherite_sword
custom-model-data: 1
unbreakable: true
unenchantable: true
unique: true
lore:
  - '<grey>Poison Immunity'
  - ''
  - '<white>Unleashs poisonous fangs.'
enchantments:
  blanktopia:soulbound: 1
  sharpness: 7
  sweeping_edge: 3
  looting: 4
  blanktopia:sting: 3
slots: [HAND, OFF_HAND]
triggers:
  damaged:
    - type: immunity
      causes: [POISON]
  left-click-block:
    - type: if
      if:
        type: attack-cooldown
      then:
        - type: evoker-fang
          location:
            type: block
  damage-entity:
    - type: if
      if:
        type: attack-cooldown
      then:
        - type: evoker-fang
