version: 1
name: "Beginner's Grappling Hook"
item: wooden_hoe
custom-model-data: 1009
soulbound: true
unenchantable: true
unbreakable: true
unique: true
lore:
  - ''
  - '<white>Allows you to fire a grappling'
  - '<white>hook by pressing <aqua>F<white>.'
  - '<white>Press <aqua>Sneak<white> to release.'
  - ''
  - '<white>Type <aqua>/trinkets<white> to open your'
  - '<white>trinket bag.'
  - ''
  - '<grey>Range: 15 blocks'
  - '<grey>Speed: Slow'
  - ''
  - '<grey>Slot: <#ff4e1d>Trinket'
slots:
  - TRINKET
triggers:
  right-click:
    - type: launch-grapple
      speed: 2.0
    - type: cancel
  swap-hand:
    - type: launch-grapple
      speed: 2.0
    - type: cancel
  projectile-tick:
    - type: grapple-tick
      acceleration: 0.15
      max-speed: 0.3
      detach-speed: 0.5
      range: 15
