name: "Beginner's Grappling Hook"
material: WOODEN_HOE
custom-model-data: 1009

unique: true
unbreakable: true

lore: |-
  &8-------------------------
  &7Slot: &#ff4e1d&Trinket

  &fAllows you to fire a grappling
  &fhook by pressing &bF&f.
  &fPress &bSneak&f to release.

  &fType &b/trinkets&f to open your
  &ftrinket bag.
  
  &7Range: 15 blocks
  &7Speed: Slow
  &8-------------------------

enchantments:
  blanktopia:soulbound: 1
  blanktopia:final: 1

slots:
- TRINKET

triggers:
  right-click:
  - type: launch-grapple
    speed: 1.0
  - type: cancel
  swap-hand:
  - type: launch-grapple
    speed: 1.0
  - type: cancel
  projectile-tick:
  - type: grapple-tick
    acceleration: 0.2
    max-speed: 0.3
    range: 15
