version: 1
name: "<white>Onigiri"
item: cookie
custom-model-data: 8
enchantments:
  blanktopia:soulbound: 1
enchantment-glint: false
unenchantable: true
lore:
  - ''
  - '<white>Soulbound items stay with you when you die.'
triggers:
  consume:
    - type: feed
      amount: 3
      saturation: 5.6
    - type: add-potion-effect
      duration: 1200
      effect: damage_resistance
      level: 1
