version: 1
name: "Claim Shovel"
item: golden_shovel
enchantments:
  blanktopia:soulbound: 1
enchantment-glint: false
unenchantable: true
lore:
  - ''
  - '<white>Read <aqua>/claims<white> for more information.'
unbreakable: true
triggers:
  break-block:
    - type: cancel
