version: 1
name: Beginner's Guide
item: knowledge_book
soulbound: true
unenchantable: true
lore:
  - '<aqua>Right-click<white> or type <aqua>/help<white> to learn more'
  - '<white>about Blanktopia.'
triggers:
  right-click:
    - type: player-command
      command: help
    - type: cancel
  right-click-inventory:
    - type: player-command
      command: help
    - type: cancel
