name: "&x&f&4&c&f&8&bBoots of Haste \U0001FAB6"
material: LEATHER_BOOTS
custom-model-data: 1

lore: |-
  &8-------------------------

  &fMove fast and break things.

  &8-------------------------
  &6NATURE Crate Item

unbreakable: true

enchantments:
  depth_strider: 3
  feather_falling: 4
  blanktopia:final: 1
  protection: 4
  soul_speed: 3
  blanktopia:soulbound: 1
  blanktopia:stride: 5

attributes:
- amount: 0.2
  attribute: GENERIC_MOVEMENT_SPEED
  name: Movement speed
  operation: MULTIPLY_SCALAR_1
  slot: FEET
  uuid: c5f2fe33-1f7f-41c5-872c-5868739f409a

triggers:
  sprint:
  - type: if
    if:
      type: is-on-ground
    then:
    - type: add-velocity
      x: 0
      y: 0
      z: 0.7
    - type: repeat
      count: 3
      interval: 3
      actions:
      - type: spawn-particle
        count: 2
        y: 0.9
        offset-x: 0.3
        offset-y: 0.1
        offset-z: 0.3
        particle: CLOUD
        extra: 0
