name: "&dHummingbird&5 ⭐"
material: ELYTRA

lore: |-
  &8-------------------------
  
  &fAllows you to hover in claims
  &fyou are &b/trusted&f in.
  
  &8-------------------------
  &6BUILDER's Crate Item

unbreakable: true

enchantments:
  blanktopia:final: 1
  blanktopia:soulbound: 1

slots:
- CHEST

triggers:
  equip-chest:
  - type: fly-in-claims
    fly: true
  unequip-armor:
  - type: fly-in-claims
    fly: false
  tick-slow:
  - type: if
    if: 
      type: is-flying
    then:
    - type: spawn-particle
      count: 10
      y: 0.9
      offset-x: 0.3
      offset-y: 0.3
      offset-z: 0.3
      particle: SUSPENDED
      extra: 0
