name: "&x&f&f&d&7&4&7Miner's Helmet"
material: GLOWSTONE_DUST
custom-model-data: 1

lore: |-
  &7Haste II
  &8-------------------------
  
  &fSpelunky!
  
  &8-------------------------
  &6MINER's Crate Item

unbreakable: true

enchantments:
  aqua_affinity: 1
  blast_protection: 4
  blanktopia:nightvision: 1
  blanktopia:final: 1
  blanktopia:soulbound: 1

attributes:
- amount: 3
  attribute: GENERIC_ARMOR
  name: Armor modifier
  operation: ADD_NUMBER
  slot: HEAD
  uuid: b8408cd3-3181-462e-b674-32ea3278c2ac
- amount: 3
  attribute: GENERIC_ARMOR_TOUGHNESS
  name: Armor toughness
  operation: ADD_NUMBER
  slot: HEAD
  uuid: 6d310b8b-3d32-4d7a-a498-985a516e35e6
- amount: 0.1
  attribute: GENERIC_KNOCKBACK_RESISTANCE
  name: Knockback resistance
  operation: ADD_NUMBER
  slot: HEAD
  uuid: 57560b26-fada-4ab2-9979-f534f05ffd7f

triggers:
  equip-head:
  - type: add-permanent-potion-effect
    key: miners-helmet
    effects: { fast_digging: 1 }
  unequip-armor:
  - type: remove-permanent-potion-effect
    key: miners-helmet
  right-click:
  - type: if
    if:
      type: equip-item
      slot: HEAD
    then:
    - type: cancel
  right-click-inventory:
  - type: if
    if:
      type: equip-item
      slot: HEAD
    then:
    - type: cancel
  shift-right-click-inventory:
  - type: if
    if:
      type: equip-item
      slot: HEAD
    then:
    - type: cancel
  shift-left-click-inventory:
  - type: if
    if:
      type: equip-item
      slot: HEAD
    then:
    - type: cancel