name: "§x§e§5§7§b§b§1Sandy's Helmet ⭐"
material: WHITE_STAINED_GLASS

lore: |-
  &7Water Breathing
  &8-------------------------
  
  &fUpside down fish bowl.
  
  &8-------------------------
  &6INFINITY Crate Item

unbreakable: true

enchantments:
  aqua_affinity: 1
  blast_protection: 4
  blanktopia:nightvision: 1
  blanktopia:final: 1
  blanktopia:soulbound: 1

attributes:
- amount: 3
  attribute: GENERIC_ARMOR
  name: Armor modifier
  operation: ADD_NUMBER
  slot: HEAD
  uuid: 25e327b5-6976-41d3-a6d8-9721265d514d
- amount: 3
  attribute: GENERIC_ARMOR_TOUGHNESS
  name: Armor toughness
  operation: ADD_NUMBER
  slot: HEAD
  uuid: 84ef93c4-4b9a-4a11-8c7d-5c48a5baa510
- amount: 0.1
  attribute: GENERIC_KNOCKBACK_RESISTANCE
  name: Knockback resistance
  operation: ADD_NUMBER
  slot: HEAD
  uuid: 940c1660-5609-4065-a5fe-fbd9d2fd7d08

triggers:
  equip-head:
  - type: add-permanent-potion-effect
    key: sandys-helmet
    effects: { water_breathing: 0 }
  unequip-armor:
  - type: remove-permanent-potion-effect
    key: sandys-helmet
