name: "<aqua>2x EXP Coupon (Server-wide)"
material: PAPER
custom-model-data: 1
model: "blanktopia:misc/exp_coupon"
lore:
  - '<dark_grey>-------------------------'
  - ''
  - '<aqua>Right-click<white> to grant a <aqua>2x EXP<white>'
  - '<white>buff to all online <white>players'
  - '<white>for <aqua>15 minutes<white>.'
  - ''
  - '<dark_grey>-------------------------'
enchantments:
  final: 1
triggers:
  right-click:
    - type: all-players
      actions:
        - type: experience-boost
          multiplier: 2
          duration: 18000
        - type: play-sound
          sound: entity.experience_orb.pickup
        - type: play-sound
          sound: block.enchantment_table.use
    - type: console-command
      command: broadcast <gold>%p<gold> has given everyone a <aqua>2x EXP buff<gold> for 15 minutes.
    - type: remove-item
