name: "&b2x EXP Coupon (Server-wide)"
material: PAPER
custom-model-data: 1
model: "blanktopia:misc/exp_coupon"
lore:
  - '&8-------------------------'
  - ''
  - '&bRight-click&f to grant a &b2x EXP&f'
  - '&fbuff to all online &fplayers'
  - '&ffor &b15 minutes&f.'
  - ''
  - '&8-------------------------'
enchantments:
  final: 1
triggers:
  right-click:
    - type: all-players
      actions:
        - type: experience-boost
          multiplier: 2
          duration: 18000
        - type: play-sound
          sound: entity.experience_orb.pickup
        - type: play-sound
          sound: block.enchantment_table.use
    - type: console-command
      command: broadcast &6%p&6 has given everyone a &b2x EXP buff&6 for 15 minutes.
    - type: remove-item
