name: "&b3x EXP Coupon"
material: PAPER
custom-model-data: 1

lore: |-
  &8-------------------------
  
  &bRight-click&f to receive a
  &b3x EXP&f buff for &b5 minutes&f.
  
  &8-------------------------

enchantments:
  final: 1

triggers:
  right-click:
  - type: experience-boost
    multiplier: 3
    duration: 6000
  - type: message
    message: "&6Received &b3x EXP&6 buff for 5 minutes."
  - type: play-sound
    sound: entity.experience_orb.pickup
  - type: play-sound
    sound: block.enchantment_table.use
  - type: remove-item
