name: "<aqua>3x EXP Coupon"
item: paper
custom-model-data: 1
model: "blanktopia:misc/exp_coupon"
lore:
  - '<dark_grey>-------------------------'
  - ''
  - '<aqua>Right-click<white> to receive a'
  - '<aqua>3x EXP<white> buff for <aqua>5 minutes<white>.'
  - ''
  - '<dark_grey>-------------------------'
enchantments:
  final: 1
triggers:
  right-click:
    - type: experience-boost
      multiplier: 3
      duration: 6000
    - type: message
      message: "<gold>Received <aqua>3x EXP<gold> buff for 5 minutes."
    - type: play-sound
      sound: entity.experience_orb.pickup
    - type: play-sound
      sound: block.enchantment_table.use
    - type: remove-item
