name: "&bFood Coupon (Server-wide)"
material: PAPER
custom-model-data: 3
model: "blanktopia:misc/food_coupon"

lore: |-
  &8-------------------------

  &bRight-click&f to feed all online
  &fplayers.

  &8-------------------------

enchantments:
  final: 1

triggers:
  right-click:
  - type: all-players
    actions:
    - type: add-potion-effect
      effect: saturation
      level: 0
      duration: 60
    - type: play-sound
      sound: entity.experience_orb.pickup
    - type: play-sound
      sound: block.enchantment_table.use
  - type: console-command
    command: broadcast &6%p&6 has refilled everyone's hunger.
  - type: remove-item
