name: "<aqua>Food Coupon (Server-wide)"
material: PAPER
custom-model-data: 3
model: "blanktopia:misc/food_coupon"
lore:
  - '<dark_grey>-------------------------'
  - ''
  - '<aqua>Right-click<white> to feed all online'
  - '<white>players.'
  - ''
  - '<dark_grey>-------------------------'
enchantments:
  final: 1
triggers:
  right-click:
    - type: all-players
      actions:
        - type: add-potion-effect
          effect: saturation
          level: 0
          duration: 60
        - type: play-sound
          sound: entity.experience_orb.pickup
        - type: play-sound
          sound: block.enchantment_table.use
    - type: console-command
      command: broadcast <gold>%p<gold> has refilled everyone's hunger.
    - type: remove-item
