name: "&bHealth Coupon (Server-wide)"
material: PAPER
custom-model-data: 2
model: "blanktopia:misc/health_coupon"

lore: |-
  &8-------------------------

  &bRight-click&f to heal all online
  &fplayers.

  &8-------------------------

enchantments:
  final: 1

triggers:
  right-click:
  - type: all-players
    actions:
    - type: add-potion-effect
      effect: regeneration
      level: 5
      duration: 60
    - type: play-sound
      sound: entity.experience_orb.pickup
    - type: play-sound
      sound: block.enchantment_table.use
  - type: console-command
    command: broadcast &6%p&6 has healed everyone.
  - type: remove-item
