name: "<aqua>Health Coupon (Server-wide)"
item: paper
custom-model-data: 2
model: "blanktopia:misc/health_coupon"
lore:
  - '<dark_grey>-------------------------'
  - ''
  - '<aqua>Right-click<white> to heal all online'
  - '<white>players.'
  - ''
  - '<dark_grey>-------------------------'
enchantments:
  final: 1
triggers:
  right-click:
    - type: all-players
      actions:
        - type: add-potion-effect
          effect: regeneration
          level: 5
          duration: 60
        - type: play-sound
          sound: entity.experience_orb.pickup
        - type: play-sound
          sound: block.enchantment_table.use
    - type: console-command
      command: tellraw @a ["",{"text":"%p","color":"gold"},{"text":" has healed everyone.","color":"gold"}]
    - type: remove-item
