namespace: blanktopia
discover-all-recipes: true
tick-interval: 1
tick-slow-interval: 5
projectile-tick-interval: 2
resource-pack-url: https://files.blanktopia.com/Blanktopia-5c782ce1b30a51df594eda2d48ffa68b0845eb56.zip
resource-pack-hash: 5c782ce1b30a51df594eda2d48ffa68b0845eb56
render-distance: 32
render-interval: 3
force-migration: false
