namespace: blanktopia
discover-all-recipes: true
tick-interval: 1
tick-slow-interval: 5
projectile-tick-interval: 2
resource-pack-url: https://files.blanktopia.com/Blanktopia-6d11af674b91e9ef88bc6ea8d06115e6c6b4d0a4.zip
resource-pack-hash: 6d11af674b91e9ef88bc6ea8d06115e6c6b4d0a4
render-distance: 32
render-interval: 3
force-migration: false
