namespace: blanktopia
discover-all-recipes: true
tick-interval: 1
tick-slow-interval: 5
projectile-tick-interval: 2
resource-pack-url: https://files.blanktopia.com/Blanktopia-ce458e49dd1e517e749a97c9f9c52df5b4cd5c8b.zip
resource-pack-hash: ce458e49dd1e517e749a97c9f9c52df5b4cd5c8b
render-distance: 32
render-interval: 3
force-migration: false
